package com.travelagent.service.notification;

public enum SseEvent {
    STATE_CHANGE,
    STEP_DONE,
    TOOL_RESULT,
    TOOL_DEGRADED,
    TOOL_RESULT_VALIDATION_WARNING,
    LLM_STREAM,
    USER_SELECTION_REQUIRED,
    USER_SELECTION_CONFIRMED,
    AUTO_SELECTION_APPLIED,
    PAUSED,
    COMPLETED,
    ERROR,
    PROGRESS_SNAPSHOT,
    RETRY,
    REWIND
}
